In [2]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from selenium.webdriver.chrome.options import Options
import sys
import regex as re
import pandas as pd

In [3]:
nombres = pd.read_csv('Data/nombresesp.csv')
Metros = pd.read_csv('Data/metrosesp.csv')
pistas = pd.read_csv('Data/pistasesp.csv')
remontes = pd.read_csv('Data/remontesesp.csv')
precios = pd.read_csv('Data/preciosesp.csv')
temporada = pd.read_csv('Data/Seasonesp.csv')

In [4]:
dfINAL = pd.concat([nombres,Metros,pistas,remontes,precios,temporada], axis=1)

In [5]:
dfINAL = dfINAL.drop('Unnamed: 0', 1)

<ipython-input-5-448f5175fe73>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  dfINAL = dfINAL.drop('Unnamed: 0', 1)

In [6]:
def limpia_col(dfcol):
    for i in dfcol:
        a = dfcol.str.extract('((\d+)+(\.\d+)|(\d+))', flags=0)
        a = a.rename(columns={0:"Primera"})
    return a.Primera

In [7]:
dfINAL['Minima Altura'] = limpia_col(dfINAL['Minima Altura'])
dfINAL['Maxima Altura'] = limpia_col(dfINAL['Maxima Altura'])
dfINAL['Adults'] = limpia_col(dfINAL['Adults'])
dfINAL['Children'] = limpia_col(dfINAL['Children'])
dfINAL['Youth'] = limpia_col(dfINAL['Youth'])

In [8]:
lista1 = []
def quitar__(dfcol):
    for i in dfcol:
        try:
            a=i.replace("__", "")
            lista1.append(a)
        except:
            lista1.append('nan')
    a =  pd.DataFrame(lista1)
    dfcol = a[0]

In [9]:
quitar__(dfINAL.Current_season_finish)

In [10]:
lista1 = []
for i in dfINAL['Current_season_finish']:
    try:
        a=i.replace("__", "")
        lista1.append(a)
    except:
        lista1.append('nan')

In [11]:
a = pd.DataFrame(lista1)

In [12]:
dfINAL['Current_season_finish'] = a[0]

In [13]:
lista2 = []
for i in dfINAL['General_season_finish']:
    try:
        a = i.replace("__", "")
        lista2.append(a)
    except:
        lista1.append('nan')

In [14]:
b = pd.DataFrame(lista2)

In [15]:
dfINAL['General_season_finish'] = b[0]

In [16]:
lista3 = []
for i in dfINAL['Closing_time']:
    try:
        a=i.replace("__", "")
        lista3.append(a)
    except:
        lista3.append('nan')

In [17]:
c = pd.DataFrame(lista3)

In [18]:
dfINAL['Closing_time'] = c[0]

In [19]:
dfINAL.rename(columns=lambda x: x.replace('Nombre', 'Name'), inplace=True)
dfINAL.rename(columns=lambda x: x.replace('Minima Altura', 'Min_Altitude'), inplace=True)
dfINAL.rename(columns=lambda x: x.replace('Maxima Altura', 'Max_Altitude'), inplace=True)
dfINAL.rename(columns=lambda x: x.replace('Pistas_Totales', 'Total_ski_routes'), inplace=True)

In [21]:
dfINAL

,Name,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Baqueira/Beret,1500,2610,160.0,80.0,60.0,20.0,5.0,29.0,54.50,36,NaN,2021-11-27,2022-04-18,early December,mid April,08:45,16:45
1,Formigal,1501,2251,137.0,47.0,70.0,20.0,NaN,15.0,49.50,40,NaN,2021-11-27,2022-04-18,late November,mid April,09:00,17:00
2,La Molina/Masella – Alp2500,1616,2531,141.0,76.0,47.0,18.0,NaN,28.0,48,44,38,2021-11-27,2022-04-18,late November,late April,09:00,16:00
3,Sierra Nevada – Pradollano,2100,3282,107.0,50.0,49.0,7.8,NaN,17.0,52,34,NaN,2021-12-04,2022-04-18,late November,early May,09:00,16:45
4,Cerler,1505,2630,81.0,37.0,29.0,15.0,NaN,13.0,46.50,37.50,NaN,2021-12-04,2022-04-18,early December,early April,09:00,16:30
5,Panticosa,1146,2204,35.0,11.0,21.0,3.0,NaN,10.0,NaN,NaN,NaN,NaN,nan,early December,early April,09:00,17:00
6,Boí Taüll,2020,2751,41.3,10.0,22.7,8.6,2.7,7.0,NaN,NaN,NaN,NaN,nan,NaN,early April,NaN,nan
7,Espot Esqui,1510,2291,25.0,13.0,8.0,4.0,NaN,3.0,NaN,NaN,NaN,NaN,nan,early December,early April,09:00,16:00
8,Candanchú,1514,2236,50.0,15.8,18.3,15.9,11.2,21.0,45,37,NaN,2021-12-04,2022-04-18,early December,early April,09:00,17:00
9,Astún,1655,2272,39.9,16.8,18.8,4.3,10.1,12.0,NaN,NaN,NaN,NaN,nan,NaN,early April,NaN,nan
10,Port del Comte,1745,2310,40.0,20.0,15.0,5.0,NaN,14.0,NaN,NaN,NaN,NaN,nan,NaN,early April,NaN,nan
11,Valdezcaray,1548,2135,22.0,10.0,10.0,2.0,2.0,10.0,NaN,NaN,NaN,NaN,nan,NaN,early April,09:00,17:00
12,Port Ainé,1650,2421,26.7,10.7,11.7,4.3,NaN,6.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
13,La Pinilla,1484,2036,21.0,14.0,6.0,1.0,NaN,11.0,NaN,NaN,NaN,NaN,nan,early December,NaN,09:00,16:30
14,Alto Campoo,1650,2120,27.7,13.6,10.9,3.2,NaN,13.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
15,Valgrande Pajares,1455,1840,25.0,12.0,10.0,3.0,NaN,8.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
16,San Isidro-Zona Cebolledo,1640,2030,20.8,6.8,9.5,4.5,3.5,7.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
17,La Covatilla – Sierra de Béjar,1990,2368,26.8,8.6,18.2,0.0,NaN,3.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
18,Valdesquí,1860,2278,22.3,18.8,3.5,0.0,NaN,13.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:30
19,Puerto Navacerrada,1703,2174,10.0,3.0,6.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
20,Javalambre,1650,2000,15.0,14.0,1.0,0.0,NaN,7.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,17:00
21,Fuentes de Invierno,1487,1950,8.8,4.2,3.3,1.3,NaN,4.0,27,22,NaN,2021-12-04,2022-04-03,early December,NaN,09:00,16:45
22,Manzaneda,1505,1760,10.0,8.0,2.0,0.0,NaN,6.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
23,Valdelinares (Sierra de Gúdar),1737,1979,17.0,10.0,7.0,0.0,NaN,9.0,NaN,NaN,NaN,NaN,nan,early December,NaN,08:30,17:00
24,Vallter 2000,1959,2535,10.4,5.4,4.0,1.0,6.3,8.0,NaN,NaN,NaN,NaN,nan,early December,NaN,09:00,16:45
25,Leitariegos,1513,1800,7.0,4.0,3.0,0.0,NaN,6.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
26,Pleta del Prat – Tavascan,1712,2197,5.0,1.0,4.0,0.0,NaN,2.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00
27,Vall de Núria,1964,2260,7.6,4.1,2.5,1.0,NaN,5.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
28,San Isidro-Zona Salencias,1502,1670,6.5,2.9,3.6,0.0,NaN,4.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
29,Rasos de Peguera,1825,2035,5.0,3.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
30,Madrid Snow Zone,667,705,0.3,0.2,0.1,0.0,NaN,3.0,NaN,NaN,NaN,NaN,nan,Year-round__,NaN,09:00,22:00
31,Punto de Nieve Santa Inés,1753,1832,1.8,1.0,0.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan

In [20]:
a = dfINAL.Min_Altitude

In [ ]:
listOfStrings1 = ['Europe'] *