In [1]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from selenium.webdriver.chrome.options import Options
import sys
import regex as re
import pandas as pd

In [2]:
nombres = pd.read_csv('Data/name.csv')
Metros = pd.read_csv('Data/metros.csv')
pistas = pd.read_csv('Data/pistas.csv')
remontes = pd.read_csv('Data/remontes.csv')
precios = pd.read_csv('Data/precios.csv')
temporada = pd.read_csv('Data/Season.csv')

In [3]:
dfINAL = pd.concat([nombres,Metros,pistas,remontes,precios,temporada], axis=1)

In [4]:
dfINAL = dfINAL.drop('Unnamed: 0', 1)

<ipython-input-4-448f5175fe73>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  dfINAL = dfINAL.drop('Unnamed: 0', 1)

In [5]:
dfINAL

,Nombre,Minima Altura,Maxima Altura,Pistas_Totales,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,__1004 m,2100 m,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,"25,-__",2021-12-04,2022-04-18__,early December,mid April__,08:30,16:30__
1,Latemar – Obereggen/Pampeago/Predazzo,__ 1540 m,2388 m,49.0,9.3,32.8,6.9,NaN,18.0,"52,-","37,-__",NaN,2021-11-26,2022-04-18__,late November,late April__,08:30,16:30__
2,Arosa Lenzerheide,__1229 m,2865 m,225.0,110.0,87.0,28.0,NaN,43.0,"78,- approx.","51,- approx.","25,-__",2021-10-30,2022-04-18__,early November,mid April__,08:30,16:30__
3,Ischgl/Samnaun – Silvretta Arena,__1360 m,2872 m,239.0,47.0,143.0,49.0,15.0,41.0,"55,-",34.50__,NaN,2021-11-25,2022-05-01__,late November,early May__,08:30,16:00__
4,Ski Juwel Alpbachtal Wildschönau,__830 m,2025 m,90.9,25.1,53.1,12.7,16.3,46.0,"51,-","41,-",25.50__,2021-12-03,2022-04-18__,mid December,mid April__,08:30,16:00__
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,__440 m,780 m,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00__
933,Eikedalen,__457 m,918 m,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00__
934,Valbella – Gallio,__1100 m,1311 m,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
935,Caldirola – Monte Gropà,__1075 m,1429 m,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08:30,17:00__
936,Kreuzberg – Bischofsheim an der Rhön,__610 m,928 m,13.0,5.0,8.0,0.0,NaN,4.0,"17,-","13,-__",NaN,2021-12-25,2022-03-13__,mid December,mid March__,09:00,17:00__

In [6]:
def limpia_col(dfcol):
    for i in dfcol:
        a = dfcol.str.extract('((\d+)+(\.\d+)|(\d+))', flags=0)
        a = a.rename(columns={0:"Primera"})
    return a.Primera

In [7]:
dfINAL['Minima Altura'] = limpia_col(dfINAL['Minima Altura'])
dfINAL['Maxima Altura'] = limpia_col(dfINAL['Maxima Altura'])
dfINAL['Adults'] = limpia_col(dfINAL['Adults'])
dfINAL['Children'] = limpia_col(dfINAL['Children'])
dfINAL['Youth'] = limpia_col(dfINAL['Youth'])

In [8]:
lista1 = []
def quitar__(dfcol):
    for i in dfcol:
        try:
            a=i.replace("__", "")
            lista1.append(a)
        except:
            lista1.append('nan')
    a =  pd.DataFrame(lista1)
    dfcol = a[0]

In [9]:
quitar__(dfINAL.Current_season_finish)

In [10]:
dfINAL

,Nombre,Minima Altura,Maxima Altura,Pistas_Totales,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,25,2021-12-04,2022-04-18__,early December,mid April__,08:30,16:30__
1,Latemar – Obereggen/Pampeago/Predazzo,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52,37,NaN,2021-11-26,2022-04-18__,late November,late April__,08:30,16:30__
2,Arosa Lenzerheide,1229,2865,225.0,110.0,87.0,28.0,NaN,43.0,78,51,25,2021-10-30,2022-04-18__,early November,mid April__,08:30,16:30__
3,Ischgl/Samnaun – Silvretta Arena,1360,2872,239.0,47.0,143.0,49.0,15.0,41.0,55,34.50,NaN,2021-11-25,2022-05-01__,late November,early May__,08:30,16:00__
4,Ski Juwel Alpbachtal Wildschönau,830,2025,90.9,25.1,53.1,12.7,16.3,46.0,51,41,25.50,2021-12-03,2022-04-18__,mid December,mid April__,08:30,16:00__
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,440,780,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00__
933,Eikedalen,457,918,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00__
934,Valbella – Gallio,1100,1311,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
935,Caldirola – Monte Gropà,1075,1429,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08:30,17:00__
936,Kreuzberg – Bischofsheim an der Rhön,610,928,13.0,5.0,8.0,0.0,NaN,4.0,17,13,NaN,2021-12-25,2022-03-13__,mid December,mid March__,09:00,17:00__

# Current season finish

In [11]:
lista1 = []
for i in dfINAL['Current_season_finish']:
    try:
        a=i.replace("__", "")
        lista1.append(a)
    except:
        lista1.append('nan')

In [12]:
a = pd.DataFrame(lista1)

In [13]:
dfINAL['Current_season_finish'] = a[0]

In [14]:
dfINAL

,Nombre,Minima Altura,Maxima Altura,Pistas_Totales,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,25,2021-12-04,2022-04-18,early December,mid April__,08:30,16:30__
1,Latemar – Obereggen/Pampeago/Predazzo,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52,37,NaN,2021-11-26,2022-04-18,late November,late April__,08:30,16:30__
2,Arosa Lenzerheide,1229,2865,225.0,110.0,87.0,28.0,NaN,43.0,78,51,25,2021-10-30,2022-04-18,early November,mid April__,08:30,16:30__
3,Ischgl/Samnaun – Silvretta Arena,1360,2872,239.0,47.0,143.0,49.0,15.0,41.0,55,34.50,NaN,2021-11-25,2022-05-01,late November,early May__,08:30,16:00__
4,Ski Juwel Alpbachtal Wildschönau,830,2025,90.9,25.1,53.1,12.7,16.3,46.0,51,41,25.50,2021-12-03,2022-04-18,mid December,mid April__,08:30,16:00__
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,440,780,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00__
933,Eikedalen,457,918,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00__
934,Valbella – Gallio,1100,1311,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN
935,Caldirola – Monte Gropà,1075,1429,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,08:30,17:00__
936,Kreuzberg – Bischofsheim an der Rhön,610,928,13.0,5.0,8.0,0.0,NaN,4.0,17,13,NaN,2021-12-25,2022-03-13,mid December,mid March__,09:00,17:00__

# General_season_finish

In [16]:
dfINAL['General_season_finish'].unique()

array(['mid April__', 'late April__', 'early May__', 'early April__',
       'late March__', 'early July__',
       'early May__mid June - early August__', nan,
       'late April__depending on snow conditions - depending on snow conditions__',
       'late April__mid June - late August__late October - early November__',
       'late May__', 'early June__', 'mid May__',
       'depending on snow conditions__',
       'late March__early July - late August__',
       'mid November__mid December - early May__', 'early March__',
       'mid March__', 'early December__late December - early May__',
       'early November__', 'mid June__'], dtype=object)

In [18]:
lista2 = []
for i in dfINAL['General_season_finish']:
    try:
        a = i.replace("__", "")
        lista2.append(a)
    except:
        lista1.append('nan')

In [19]:
b = pd.DataFrame(lista2)

In [20]:
b

               0
0      mid April
1     late April
2      mid April
3      early May
4      mid April
..           ...
667  early March
668   late March
669   late March
670    mid March
671    mid March

[672 rows x 1 columns]

In [21]:
dfINAL['General_season_finish'] = b[0]

In [22]:
dfINAL

,Nombre,Minima Altura,Maxima Altura,Pistas_Totales,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,25,2021-12-04,2022-04-18,early December,mid April,08:30,16:30__
1,Latemar – Obereggen/Pampeago/Predazzo,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52,37,NaN,2021-11-26,2022-04-18,late November,late April,08:30,16:30__
2,Arosa Lenzerheide,1229,2865,225.0,110.0,87.0,28.0,NaN,43.0,78,51,25,2021-10-30,2022-04-18,early November,mid April,08:30,16:30__
3,Ischgl/Samnaun – Silvretta Arena,1360,2872,239.0,47.0,143.0,49.0,15.0,41.0,55,34.50,NaN,2021-11-25,2022-05-01,late November,early May,08:30,16:00__
4,Ski Juwel Alpbachtal Wildschönau,830,2025,90.9,25.1,53.1,12.7,16.3,46.0,51,41,25.50,2021-12-03,2022-04-18,mid December,mid April,08:30,16:00__
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,440,780,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00__
933,Eikedalen,457,918,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00__
934,Valbella – Gallio,1100,1311,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN
935,Caldirola – Monte Gropà,1075,1429,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,08:30,17:00__
936,Kreuzberg – Bischofsheim an der Rhön,610,928,13.0,5.0,8.0,0.0,NaN,4.0,17,13,NaN,2021-12-25,2022-03-13,mid December,NaN,09:00,17:00__

# Closing_time

In [23]:
lista3 = []
for i in dfINAL['Closing_time']:
    try:
        a=i.replace("__", "")
        lista3.append(a)
    except:
        lista3.append('nan')

In [24]:
c = pd.DataFrame(lista3)

In [25]:
dfINAL['Closing_time'] = c[0]

In [26]:
dfINAL

,Nombre,Minima Altura,Maxima Altura,Pistas_Totales,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,25,2021-12-04,2022-04-18,early December,mid April,08:30,16:30
1,Latemar – Obereggen/Pampeago/Predazzo,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52,37,NaN,2021-11-26,2022-04-18,late November,late April,08:30,16:30
2,Arosa Lenzerheide,1229,2865,225.0,110.0,87.0,28.0,NaN,43.0,78,51,25,2021-10-30,2022-04-18,early November,mid April,08:30,16:30
3,Ischgl/Samnaun – Silvretta Arena,1360,2872,239.0,47.0,143.0,49.0,15.0,41.0,55,34.50,NaN,2021-11-25,2022-05-01,late November,early May,08:30,16:00
4,Ski Juwel Alpbachtal Wildschönau,830,2025,90.9,25.1,53.1,12.7,16.3,46.0,51,41,25.50,2021-12-03,2022-04-18,mid December,mid April,08:30,16:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,440,780,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00
933,Eikedalen,457,918,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00
934,Valbella – Gallio,1100,1311,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
935,Caldirola – Monte Gropà,1075,1429,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,08:30,17:00
936,Kreuzberg – Bischofsheim an der Rhön,610,928,13.0,5.0,8.0,0.0,NaN,4.0,17,13,NaN,2021-12-25,2022-03-13,mid December,NaN,09:00,17:00

In [27]:
dfINAL.sample(10)

,Nombre,Minima Altura,Maxima Altura,Pistas_Totales,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
321,Vals 3000 – Dachberg,1286,2941,25.0,5.0,15.0,5.0,NaN,5.0,30,NaN,NaN,2021-12-18,2022-04-18,mid December,late March,09:00,16:30
706,Parâng,1300,1720,8.0,0.6,4.3,3.1,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
852,Haukelifjell Skisenter,855,1216,14.2,2.4,9.2,2.6,NaN,6.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,10:00,16:00
308,Gourette (Eaux Bonnes),1350,2450,35.0,18.0,13.0,4.0,NaN,9.0,38,32.50,NaN,2021-12-11,2022-04-03,early December,early April,08:45,17:00
387,Wasserngrat – Gstaad,1275,1900,9.3,3.5,3.6,2.2,NaN,1.0,NaN,NaN,NaN,NaN,nan,mid December,late March,09:30,16:30
1,Latemar – Obereggen/Pampeago/Predazzo,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52,37,NaN,2021-11-26,2022-04-18,late November,late April,08:30,16:30
569,Sattel – Hochstuckli,800,1491,12.0,6.0,6.0,0.0,2.0,5.0,36,30,18,2021-12-04,2022-03-20,mid December,mid March,09:00,16:15
158,Bad Kleinkirchheim,1087,2055,103.0,18.0,77.0,8.0,5.0,22.0,52.50,40,26.50,2021-12-03,2022-04-03,early December,early April,09:00,16:00
133,Kreischberg,868,2118,42.5,17.5,16.0,9.0,NaN,13.0,52,41.50,26,2021-12-04,2022-04-03,early December,late April,08:30,16:00
482,Gaissau-Hintersee,750,1567,30.0,20.0,9.0,1.0,NaN,8.0,41,32,18,2021-12-11,2022-04-03,mid December,mid June,09:00,16:00

In [31]:
dfINAL.rename(columns=lambda x: x.replace('Nombre', 'Name'), inplace=True)

In [33]:
dfINAL.rename(columns=lambda x: x.replace('Minima Altura', 'Min_Altitude'), inplace=True)

In [34]:
dfINAL.rename(columns=lambda x: x.replace('Maxima Altura', 'Max_Altitude'), inplace=True)

In [35]:
dfINAL.rename(columns=lambda x: x.replace('Pistas_Totales', 'Total_ski_routes'), inplace=True)

In [36]:
dfINAL

,Name,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,25,2021-12-04,2022-04-18,early December,mid April,08:30,16:30
1,Latemar – Obereggen/Pampeago/Predazzo,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52,37,NaN,2021-11-26,2022-04-18,late November,late April,08:30,16:30
2,Arosa Lenzerheide,1229,2865,225.0,110.0,87.0,28.0,NaN,43.0,78,51,25,2021-10-30,2022-04-18,early November,mid April,08:30,16:30
3,Ischgl/Samnaun – Silvretta Arena,1360,2872,239.0,47.0,143.0,49.0,15.0,41.0,55,34.50,NaN,2021-11-25,2022-05-01,late November,early May,08:30,16:00
4,Ski Juwel Alpbachtal Wildschönau,830,2025,90.9,25.1,53.1,12.7,16.3,46.0,51,41,25.50,2021-12-03,2022-04-18,mid December,mid April,08:30,16:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,440,780,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00
933,Eikedalen,457,918,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00
934,Valbella – Gallio,1100,1311,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
935,Caldirola – Monte Gropà,1075,1429,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,08:30,17:00
936,Kreuzberg – Bischofsheim an der Rhön,610,928,13.0,5.0,8.0,0.0,NaN,4.0,17,13,NaN,2021-12-25,2022-03-13,mid December,NaN,09:00,17:00

In [38]:
a = dfINAL.Min_Altitude

In [49]:
listOfStrings1 = ['Europe'] * 937

In [50]:
dfloc = pd.DataFrame(listOfStrings1)

In [51]:
dfloc
dfloc = dfloc.rename(columns={0:"Contintent"})

In [52]:
dfloc

    Contintent
0       Europe
1       Europe
2       Europe
3       Europe
4       Europe
..         ...
932     Europe
933     Europe
934     Europe
935     Europe
936     Europe

[937 rows x 1 columns]

In [54]:
dfINAL.insert(1, 'Continent', listOfStrings1)

In [55]:
dfINAL

,Name,Continent,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,Europe,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,25,2021-12-04,2022-04-18,early December,mid April,08:30,16:30
1,Latemar – Obereggen/Pampeago/Predazzo,Europe,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52,37,NaN,2021-11-26,2022-04-18,late November,late April,08:30,16:30
2,Arosa Lenzerheide,Europe,1229,2865,225.0,110.0,87.0,28.0,NaN,43.0,78,51,25,2021-10-30,2022-04-18,early November,mid April,08:30,16:30
3,Ischgl/Samnaun – Silvretta Arena,Europe,1360,2872,239.0,47.0,143.0,49.0,15.0,41.0,55,34.50,NaN,2021-11-25,2022-05-01,late November,early May,08:30,16:00
4,Ski Juwel Alpbachtal Wildschönau,Europe,830,2025,90.9,25.1,53.1,12.7,16.3,46.0,51,41,25.50,2021-12-03,2022-04-18,mid December,mid April,08:30,16:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,Europe,440,780,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00
933,Eikedalen,Europe,457,918,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,nan,NaN,NaN,09:00,16:00
934,Valbella – Gallio,Europe,1100,1311,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,nan
935,Caldirola – Monte Gropà,Europe,1075,1429,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,08:30,17:00
936,Kreuzberg – Bischofsheim an der Rhön,Europe,610,928,13.0,5.0,8.0,0.0,NaN,4.0,17,13,NaN,2021-12-25,2022-03-13,mid December,NaN,09:00,17:00

In [56]:
dfINAL.to_csv("Data/EuropaFin.csv")