In [126]:
import pandas as pd

In [127]:
dfEu = pd.read_csv("Data/EuropaFin.csv")

In [274]:
dfesp = pd.read_csv("Data/dfespañafinal")

In [129]:
dfUSA = pd.read_csv("Data/USAFin.csv")

In [130]:
dfEu

,Unnamed: 0,Name,Continent,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,0,Lermoos – Grubigstein,Europe,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.5,39.5,25.0,2021-12-04,2022-04-18,early December,mid April,08:30,16:30
1,1,Latemar – Obereggen/Pampeago/Predazzo,Europe,1540,2388,49.0,9.3,32.8,6.9,NaN,18.0,52.0,37.0,NaN,2021-11-26,2022-04-18,late November,late April,08:30,16:30
2,2,Arosa Lenzerheide,Europe,1229,2865,225.0,110.0,87.0,28.0,NaN,43.0,78.0,51.0,25.0,2021-10-30,2022-04-18,early November,mid April,08:30,16:30
3,3,Ischgl/Samnaun – Silvretta Arena,Europe,1360,2872,239.0,47.0,143.0,49.0,15.0,41.0,55.0,34.5,NaN,2021-11-25,2022-05-01,late November,early May,08:30,16:00
4,4,Ski Juwel Alpbachtal Wildschönau,Europe,830,2025,90.9,25.1,53.1,12.7,16.3,46.0,51.0,41.0,25.5,2021-12-03,2022-04-18,mid December,mid April,08:30,16:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,932,Pallas,Europe,440,780,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00
933,933,Eikedalen,Europe,457,918,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00
934,934,Valbella – Gallio,Europe,1100,1311,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
935,935,Caldirola – Monte Gropà,Europe,1075,1429,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08:30,17:00
936,936,Kreuzberg – Bischofsheim an der Rhön,Europe,610,928,13.0,5.0,8.0,0.0,NaN,4.0,17.0,13.0,NaN,2021-12-25,2022-03-13,mid December,NaN,09:00,17:00

In [131]:
dfesp

,Unnamed: 0,Name,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,0,Baqueira/Beret,1500,2610,160.0,80.0,60.0,20.0,5.0,29.0,54.5,NaN,36.0,2021-11-27,2022-04-18,early December,mid April,08:45,16:45
1,1,Formigal,1501,2251,137.0,47.0,70.0,20.0,NaN,15.0,49.5,NaN,40.0,2021-11-27,2022-04-18,late November,mid April,09:00,17:00
2,2,La Molina/Masella – Alp2500,1616,2531,141.0,76.0,47.0,18.0,NaN,28.0,48.0,NaN,NaN,2021-11-27,2022-04-18,late November,late April,09:00,16:00
3,3,Sierra Nevada – Pradollano,2100,3282,107.0,50.0,49.0,7.8,NaN,17.0,52.0,NaN,NaN,2021-12-04,2022-04-18,late November,early May,09:00,16:45
4,4,Cerler,1505,2630,81.0,37.0,29.0,15.0,NaN,13.0,NaN,NaN,NaN,2021-12-04,2022-04-18,early December,early April,09:00,16:30
5,5,Panticosa,1146,2204,35.0,11.0,21.0,3.0,NaN,10.0,43.5,NaN,35.0,NaN,NaN,early December,early April,09:00,17:00
6,6,Boí Taüll,2020,2751,41.3,10.0,22.7,8.6,2.7,7.0,39.0,NaN,NaN,NaN,NaN,NaN,early April,NaN,NaN
7,7,Espot Esqui,1510,2291,25.0,13.0,8.0,4.0,NaN,3.0,34.0,NaN,NaN,NaN,NaN,early December,early April,09:00,16:00
8,8,Candanchú,1514,2236,50.0,15.8,18.3,15.9,11.2,21.0,45.0,NaN,NaN,2021-12-04,2022-04-18,early December,early April,09:00,17:00
9,9,Astún,1655,2272,39.9,16.8,18.8,4.3,10.1,12.0,45.0,NaN,NaN,NaN,NaN,NaN,early April,NaN,NaN
10,10,Port del Comte,1745,2310,40.0,20.0,15.0,5.0,NaN,14.0,36.0,NaN,NaN,NaN,NaN,NaN,early April,NaN,NaN
11,11,Valdezcaray,1548,2135,22.0,10.0,10.0,2.0,2.0,10.0,29.0,NaN,NaN,NaN,NaN,NaN,early April,09:00,17:00
12,12,Port Ainé,1650,2421,26.7,10.7,11.7,4.3,NaN,6.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,La Pinilla,1484,2036,21.0,14.0,6.0,1.0,NaN,11.0,35.0,NaN,NaN,NaN,NaN,early December,NaN,09:00,16:30
14,14,Alto Campoo,1650,2120,27.7,13.6,10.9,3.2,NaN,13.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,Valgrande Pajares,1455,1840,25.0,12.0,10.0,3.0,NaN,8.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,San Isidro-Zona Cebolledo,1640,2030,20.8,6.8,9.5,4.5,3.5,7.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,La Covatilla – Sierra de Béjar,1990,2368,26.8,8.6,18.2,0.0,NaN,3.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,Valdesquí,1860,2278,22.3,18.8,3.5,0.0,NaN,13.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:30
19,19,Puerto Navacerrada,1703,2174,10.0,3.0,6.0,1.0,NaN,5.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,Javalambre,1650,2000,15.0,14.0,1.0,0.0,NaN,7.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,09:00,17:00
21,21,Fuentes de Invierno,1487,1950,8.8,4.2,3.3,1.3,NaN,4.0,27.0,NaN,NaN,2021-12-04,2022-04-03,early December,NaN,09:00,16:45
22,22,Manzaneda,1505,1760,10.0,8.0,2.0,0.0,NaN,6.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,Valdelinares (Sierra de Gúdar),1737,1979,17.0,10.0,7.0,0.0,NaN,9.0,37.5,NaN,30.0,NaN,NaN,early December,NaN,08:30,17:00
24,24,Vallter 2000,1959,2535,10.4,5.4,4.0,1.0,6.3,8.0,27.0,NaN,NaN,NaN,NaN,early December,NaN,09:00,16:45
25,25,Leitariegos,1513,1800,7.0,4.0,3.0,0.0,NaN,6.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,Pleta del Prat – Tavascan,1712,2197,5.0,1.0,4.0,0.0,NaN,2.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00
27,27,Vall de Núria,1964,2260,7.6,4.1,2.5,1.0,NaN,5.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,San Isidro-Zona Salencias,1502,1670,6.5,2.9,3.6,0.0,NaN,4.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,Rasos de Peguera,1825,2035,5.0,3.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30,Madrid Snow Zone,667,705,0.3,0.2,0.1,0.0,NaN,3.0,39.0,NaN,NaN,NaN,NaN,Year-round__,NaN,09:00,22:00
31,31,Punto de Nieve Santa Inés,1753,1832,1.8,1.0,0.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [275]:
dfesp = dfesp.drop(['Youth', 'Unnamed: 0', 'Children'], axis=1)

In [133]:
dfEu = dfEu.drop(['Youth', 'Unnamed: 0', 'Children'], axis=1)

In [134]:
dfUSA = dfUSA.drop(['Youth', 'Unnamed: 0', 'Children'], axis=1)

In [276]:
dfesp.head(5)

,Name,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Baqueira/Beret,1500,2610,160.0,80.0,60.0,20.0,5.0,29.0,54.5,2021-11-27,2022-04-18,early December,mid April,08:45,16:45
1,Formigal,1501,2251,137.0,47.0,70.0,20.0,NaN,15.0,49.5,2021-11-27,2022-04-18,late November,mid April,09:00,17:00
2,La Molina/Masella – Alp2500,1616,2531,141.0,76.0,47.0,18.0,NaN,28.0,48.0,2021-11-27,2022-04-18,late November,late April,09:00,16:00
3,Sierra Nevada – Pradollano,2100,3282,107.0,50.0,49.0,7.8,NaN,17.0,52.0,2021-12-04,2022-04-18,late November,early May,09:00,16:45
4,Cerler,1505,2630,81.0,37.0,29.0,15.0,NaN,13.0,NaN,2021-12-04,2022-04-18,early December,early April,09:00,16:30

In [136]:
dfEu.head(1)

,Name,Continent,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,Europe,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.5,2021-12-04,2022-04-18,early December,mid April,08:30,16:30

In [137]:
dfUSA.head(1)

,Name,Continent,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Vail,America,2457,3433,234.0,57.0,84.0,93.0,NaN,25.0,219.0,2021-11-19,2022-04-24,mid November,mid April,08:30,16:00

In [277]:
nuevosnombres = []
for i in dfesp.Name:
    a = i.replace('– Alp2500', '')
    nuevosnombres.append(a)

In [278]:
dfesp.Name = nuevosnombres

In [279]:
dfesp.Name = dfesp.Name.str.replace("[–]|[-]", " ", regex=True)
dfEu.Name = dfEu.Name.str.replace("[–]|[-]", " ", regex=True)
dfUSA.Name = dfUSA.Name.str.replace("[–]|[-]", " ", regex=True)

In [280]:
dfesp.head(1)

,Name,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Baqueira/Beret,1500,2610,160.0,80.0,60.0,20.0,5.0,29.0,54.5,2021-11-27,2022-04-18,early December,mid April,08:45,16:45

In [281]:
dfEu.head(1)

,Name,Continent,Country,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos Grubigstein,Europe,Austria,1004,2100,27.3,12.8,12.6,1.9,1.7,8.0,49.5,2021-12-04,2022-04-18,early December,mid April,08:30,16:30

In [282]:
dfUSA.head(1)

,Name,Continent,Country,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Vail,America,United States,2457,3433,234.0,57.0,84.0,93.0,NaN,25.0,219.0,2021-11-19,2022-04-24,mid November,mid April,08:30,16:00

In [283]:
from geopy.geocoders import Nominatim

In [284]:
def coger_loc(columnaNombre):
    try:
        geolocator = Nominatim(user_agent="Jaime")
        location = geolocator.geocode(f'{columnaNombre}')
        x = location.address
        print(x)
        return (x.split(",")[-1], x.split(",")[-3], (location.latitude, location.longitude))
    except:
        return 'error'

In [285]:
coger_loc('Madrid')

Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España

(' España', ' Comunidad de Madrid', (40.4167047, -3.7035825))

In [146]:
dfesp['Country']=dfesp['Name'].apply(coger_loc)
dfEu['Country']=dfEu['Name'].apply(coger_loc)
dfUSA['Country']=dfUSA['Name'].apply(coger_loc)

In [162]:
dfesp['Continent'] = ('Europe')

In [163]:
dfesp

,Name,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time,Country,Continent
0,Baqueira/Beret,1500,2610,160.0,80.0,60.0,20.0,5.0,29.0,54.5,2021-11-27,2022-04-18,early December,mid April,08:45,16:45,España,Europe
1,Formigal,1501,2251,137.0,47.0,70.0,20.0,NaN,15.0,49.5,2021-11-27,2022-04-18,late November,mid April,09:00,17:00,España,Europe
2,La Molina/Masella,1616,2531,141.0,76.0,47.0,18.0,NaN,28.0,48.0,2021-11-27,2022-04-18,late November,late April,09:00,16:00,España,Europe
3,Sierra Nevada Pradollano,2100,3282,107.0,50.0,49.0,7.8,NaN,17.0,52.0,2021-12-04,2022-04-18,late November,early May,09:00,16:45,España,Europe
4,Cerler,1505,2630,81.0,37.0,29.0,15.0,NaN,13.0,NaN,2021-12-04,2022-04-18,early December,early April,09:00,16:30,España,Europe
5,Panticosa,1146,2204,35.0,11.0,21.0,3.0,NaN,10.0,43.5,NaN,NaN,early December,early April,09:00,17:00,España,Europe
6,Boí Taüll,2020,2751,41.3,10.0,22.7,8.6,2.7,7.0,39.0,NaN,NaN,NaN,early April,NaN,NaN,España,Europe
7,Espot Esqui,1510,2291,25.0,13.0,8.0,4.0,NaN,3.0,34.0,NaN,NaN,early December,early April,09:00,16:00,España,Europe
8,Candanchú,1514,2236,50.0,15.8,18.3,15.9,11.2,21.0,45.0,2021-12-04,2022-04-18,early December,early April,09:00,17:00,España,Europe
9,Astún,1655,2272,39.9,16.8,18.8,4.3,10.1,12.0,45.0,NaN,NaN,NaN,early April,NaN,NaN,Ísland,Europe
10,Port del Comte,1745,2310,40.0,20.0,15.0,5.0,NaN,14.0,36.0,NaN,NaN,NaN,early April,NaN,NaN,España,Europe
11,Valdezcaray,1548,2135,22.0,10.0,10.0,2.0,2.0,10.0,29.0,NaN,NaN,NaN,early April,09:00,17:00,España,Europe
12,Port Ainé,1650,2421,26.7,10.7,11.7,4.3,NaN,6.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
13,La Pinilla,1484,2036,21.0,14.0,6.0,1.0,NaN,11.0,35.0,NaN,NaN,early December,NaN,09:00,16:30,España,Europe
14,Alto Campoo,1650,2120,27.7,13.6,10.9,3.2,NaN,13.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
15,Valgrande Pajares,1455,1840,25.0,12.0,10.0,3.0,NaN,8.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
16,San Isidro Zona Cebolledo,1640,2030,20.8,6.8,9.5,4.5,3.5,7.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,error,Europe
17,La Covatilla Sierra de Béjar,1990,2368,26.8,8.6,18.2,0.0,NaN,3.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
18,Valdesquí,1860,2278,22.3,18.8,3.5,0.0,NaN,13.0,38.0,NaN,NaN,NaN,NaN,09:00,16:30,España,Europe
19,Puerto Navacerrada,1703,2174,10.0,3.0,6.0,1.0,NaN,5.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
20,Javalambre,1650,2000,15.0,14.0,1.0,0.0,NaN,7.0,36.0,NaN,NaN,NaN,NaN,09:00,17:00,España,Europe
21,Fuentes de Invierno,1487,1950,8.8,4.2,3.3,1.3,NaN,4.0,27.0,2021-12-04,2022-04-03,early December,NaN,09:00,16:45,España,Europe
22,Manzaneda,1505,1760,10.0,8.0,2.0,0.0,NaN,6.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
23,Valdelinares (Sierra de Gúdar),1737,1979,17.0,10.0,7.0,0.0,NaN,9.0,37.5,NaN,NaN,early December,NaN,08:30,17:00,España,Europe
24,Vallter 2000,1959,2535,10.4,5.4,4.0,1.0,6.3,8.0,27.0,NaN,NaN,early December,NaN,09:00,16:45,España,Europe
25,Leitariegos,1513,1800,7.0,4.0,3.0,0.0,NaN,6.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
26,Pleta del Prat Tavascan,1712,2197,5.0,1.0,4.0,0.0,NaN,2.0,22.0,NaN,NaN,NaN,NaN,09:00,16:00,error,Europe
27,Vall de Núria,1964,2260,7.6,4.1,2.5,1.0,NaN,5.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
28,San Isidro Zona Salencias,1502,1670,6.5,2.9,3.6,0.0,NaN,4.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,error,Europe
29,Rasos de Peguera,1825,2035,5.0,3.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe
30,Madrid Snow Zone,667,705,0.3,0.2,0.1,0.0,NaN,3.0,39.0,NaN,NaN,Year-round__,NaN,09:00,22:00,error,Europe
31,Punto de Nieve Santa Inés,1753,1832,1.8,1.0,0.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,España,Europe

In [213]:
dfEu[dfEu["Country"] == ' Tchad تشاد']

,Name,Continent,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time,Country
879,Golte,Europe,1150,1570,8.5,2.9,4.9,0.7,1.5,6.0,31.0,2021-12-11,2022-04-03,early December,NaN,09:00,16:00,Tchad تشاد

In [215]:
Macedonia = ' Ελλάς'
Austria = ' Österreich'
Switzerland = ' Schweiz/Suisse/Svizzera/Svizra'
Norway = ' Norge'
Sweeden = ' Sverige'
Finland = ' Suomi / Finland'
Bulgaria = ' Бългaрия'
Austria1 = ' 中国'
Czech_Republic = ' Česko'
Russia = ' Россия'
Poland = ' Polska'
Slovakia = ' Slovensko'
Serbia = ' Србија'
Ukraine = ' Україна'
Norway1 = ' Nigeria'
Bosnia = ' Bosna i Hercegovina / Босна и Херцеговина'
Scotland = ' United States'
Montenegro = ' Crna Gora / Црна Гора'
Netherlands = ' Nederland'
Slovenia = ' Slovenija'
Switzerland1 = ' Brasil'
Italia = ' Colombia'
United_Kingdom = 'Saint Kitts and Nevis'
Romania = ' România'
Macedonia1 = ' Северна Македонија'
France = ' Canada'
Romania1 = ' Luzon'
Slovenia1 = ' 日本'
Beligium = ' België / Belgique / Belgien'
España = ' Eesti'
Hungary = ' Magyarország'
Slovenia2 = ' Tchad تشاد'

In [228]:
dfEu.Country= dfEu.Country.str.replace(' Slovenija', ' Slovenia')
dfEu.Country= dfEu.Country.str.replace(' Colombia', ' Italia')
dfEu.Country= dfEu.Country.str.replace('Saint Kitts and Nevis', ' United Kingdom')
dfEu.Country= dfEu.Country.str.replace(' România', ' Romania')
dfEu.Country= dfEu.Country.str.replace(' Северна Македонија', ' Macedonia')
dfEu.Country= dfEu.Country.str.replace(' Canada', ' Romania')
dfEu.Country= dfEu.Country.str.replace(' Luzon', ' Macedonia')
dfEu.Country= dfEu.Country.str.replace(' 日本', ' Slovenia')
dfEu.Country= dfEu.Country.str.replace(' België / Belgique / Belgien', ' Beligium')
dfEu.Country= dfEu.Country.str.replace(' Eesti', ' España')
dfEu.Country= dfEu.Country.str.replace(' Magyarország', ' Hungary')
dfEu.Country= dfEu.Country.str.replace(' Tchad تشاد', ' Slovenia')

In [229]:
dfEu.Country= dfEu.Country.str.replace(' Ελλάς', ' Macedonia')
dfEu.Country= dfEu.Country.str.replace(' Österreich', ' Austria')
dfEu.Country= dfEu.Country.str.replace(' Schweiz/Suisse/Svizzera/Svizra', ' Switzerland')
dfEu.Country= dfEu.Country.str.replace(' Norge', ' Norway')
dfEu.Country= dfEu.Country.str.replace(' Sverige', ' Sweeden')
dfEu.Country= dfEu.Country.str.replace(' Suomi / Finland', ' Finland')
dfEu.Country= dfEu.Country.str.replace(' Бългaрия', ' Bulgaria')
dfEu.Country= dfEu.Country.str.replace(' 中国', ' Austria')
dfEu.Country= dfEu.Country.str.replace(' Česko', ' Czech_Republic')
dfEu.Country= dfEu.Country.str.replace(' Россия', ' Russia')
dfEu.Country= dfEu.Country.str.replace(' Polska', ' Poland')
dfEu.Country= dfEu.Country.str.replace(' Slovensko', ' Slovakia')
dfEu.Country= dfEu.Country.str.replace(' Србија', ' Serbia')
dfEu.Country= dfEu.Country.str.replace(' Україна', ' Ukraine')
dfEu.Country= dfEu.Country.str.replace(' Nigeria', ' Norway')
dfEu.Country= dfEu.Country.str.replace(' Bosna i Hercegovina / Босна и Херцеговина', ' Bosnia')
dfEu.Country= dfEu.Country.str.replace(' United States', ' Scotland')
dfEu.Country= dfEu.Country.str.replace(' Crna Gora / Црна Гора', ' Montenegro')
dfEu.Country= dfEu.Country.str.replace(' Nederland', ' Netherlands')

In [231]:
dfEu.Country= dfEu.Country.str.replace('Saint Kitts and Nevis', ' United Kingdom')

In [232]:
dfEu.Country.unique()

array([' Austria', 'error', ' Switzerland', ' Italia', ' Deutschland',
       ' France', ' Norway', ' España', ' Danmark', ' Sweeden',
       ' Finland', ' Bulgaria', ' Czech_Republic', ' Andorra', ' Russia',
       ' Poland', ' Liechtenstein', ' Slovakia', ' Serbia', ' Ukraine',
       ' Bosnia', ' Scotland', ' Montenegro', ' Netherlands', ' Slovenia',
       ' Brasil', ' Ísland', ' United Kingdom', ' Romania', ' Macedonia',
       ' Beligium', ' Hungary', ' Portugal'], dtype=object)

In [236]:
dfEu = dfEu[['Name', 'Continent', 'Country', 'Min_Altitude', 'Max_Altitude','Total_ski_routes','Easy', 'Intermediate','Difficult', 'Aditional_Routes', 'Lifts', 'Adults', 'Current_season_start', 'Current_season_finish', 'General_season_start', 'General_season_finish','Opening_time', 'Closing_time']]

In [238]:
dfEu.sample(10)

,Name,Continent,Country,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
362,Strandafjellet,Europe,Norway,430,1230,25.0,14.0,7.0,4.0,NaN,7.0,NaN,NaN,NaN,NaN,mid April,10:00,16:00
653,Cima Piazzi/San Colombano Isolaccia/Oga,Europe,error,1340,2547,9.0,0.3,8.7,0.0,NaN,9.0,40.0,2021-11-27,2022-04-18,early December,mid March,09:00,16:00
283,Laterns Gapfohl,Europe,Austria,1040,1785,27.0,8.0,15.0,4.0,11.0,5.0,39.0,2021-12-04,2022-03-27,late November,early May,08:45,16:15
906,Passolanciano,Europe,error,1300,1650,5.5,2.7,2.0,0.8,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
715,Dwie Doliny Wierchomla Mała/Szczawnik (Piwni...,Europe,error,610,1001,11.0,7.0,4.0,0.0,NaN,10.0,22.0,2021-12-04,2022-03-27,early December,NaN,09:00,18:00
561,Praděd/Myšák Malá Morávka (Ski Karlov),Europe,error,685,940,10.4,6.9,3.5,0.0,NaN,6.0,NaN,NaN,NaN,NaN,late March,09:00,16:00
133,Kreischberg,Europe,Deutschland,868,2118,42.5,17.5,16.0,9.0,NaN,13.0,52.0,2021-12-04,2022-04-03,early December,late April,08:30,16:00
564,La Bresse Hohneck,Europe,France,872,1350,21.0,13.0,7.0,1.0,1.0,16.0,32.0,2021-12-04,2022-04-03,mid December,late March,09:00,17:00
63,Laax/Flims/Falera,Europe,Switzerland,1100,3018,188.0,88.0,81.0,19.0,28.0,28.0,82.0,2021-10-30,2022-04-24,late October,early May,08:30,16:30
437,Bonneval sur Arc,Europe,France,1850,3000,32.0,9.0,19.5,3.5,NaN,10.0,29.8,2021-12-17,2022-04-24,mid December,late March,09:00,16:00

In [240]:
dfesp.Country = ' España'

In [242]:
dfesp= dfesp[['Name', 'Continent', 'Country', 'Min_Altitude', 'Max_Altitude','Total_ski_routes','Easy', 'Intermediate','Difficult', 'Aditional_Routes', 'Lifts', 'Adults', 'Current_season_start', 'Current_season_finish', 'General_season_start', 'General_season_finish','Opening_time', 'Closing_time']]

In [248]:
dfUSA.Country = ' United States'

In [249]:
dfUSA= dfUSA[['Name', 'Continent', 'Country', 'Min_Altitude', 'Max_Altitude','Total_ski_routes','Easy', 'Intermediate','Difficult', 'Aditional_Routes', 'Lifts', 'Adults', 'Current_season_start', 'Current_season_finish', 'General_season_start', 'General_season_finish','Opening_time', 'Closing_time']]

In [255]:
dffin = pd.concat([dfEu, dfesp, dfUSA], ignore_index=True)

In [272]:
dffin.to_csv("Data/global.csv")

In [286]:
dfesp

,Name,Min_Altitude,Max_Altitude,Total_ski_routes,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Baqueira/Beret,1500,2610,160.0,80.0,60.0,20.0,5.0,29.0,54.5,2021-11-27,2022-04-18,early December,mid April,08:45,16:45
1,Formigal,1501,2251,137.0,47.0,70.0,20.0,NaN,15.0,49.5,2021-11-27,2022-04-18,late November,mid April,09:00,17:00
2,La Molina/Masella,1616,2531,141.0,76.0,47.0,18.0,NaN,28.0,48.0,2021-11-27,2022-04-18,late November,late April,09:00,16:00
3,Sierra Nevada Pradollano,2100,3282,107.0,50.0,49.0,7.8,NaN,17.0,52.0,2021-12-04,2022-04-18,late November,early May,09:00,16:45
4,Cerler,1505,2630,81.0,37.0,29.0,15.0,NaN,13.0,NaN,2021-12-04,2022-04-18,early December,early April,09:00,16:30
5,Panticosa,1146,2204,35.0,11.0,21.0,3.0,NaN,10.0,43.5,NaN,NaN,early December,early April,09:00,17:00
6,Boí Taüll,2020,2751,41.3,10.0,22.7,8.6,2.7,7.0,39.0,NaN,NaN,NaN,early April,NaN,NaN
7,Espot Esqui,1510,2291,25.0,13.0,8.0,4.0,NaN,3.0,34.0,NaN,NaN,early December,early April,09:00,16:00
8,Candanchú,1514,2236,50.0,15.8,18.3,15.9,11.2,21.0,45.0,2021-12-04,2022-04-18,early December,early April,09:00,17:00
9,Astún,1655,2272,39.9,16.8,18.8,4.3,10.1,12.0,45.0,NaN,NaN,NaN,early April,NaN,NaN
10,Port del Comte,1745,2310,40.0,20.0,15.0,5.0,NaN,14.0,36.0,NaN,NaN,NaN,early April,NaN,NaN
11,Valdezcaray,1548,2135,22.0,10.0,10.0,2.0,2.0,10.0,29.0,NaN,NaN,NaN,early April,09:00,17:00
12,Port Ainé,1650,2421,26.7,10.7,11.7,4.3,NaN,6.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN
13,La Pinilla,1484,2036,21.0,14.0,6.0,1.0,NaN,11.0,35.0,NaN,NaN,early December,NaN,09:00,16:30
14,Alto Campoo,1650,2120,27.7,13.6,10.9,3.2,NaN,13.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN
15,Valgrande Pajares,1455,1840,25.0,12.0,10.0,3.0,NaN,8.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN
16,San Isidro Zona Cebolledo,1640,2030,20.8,6.8,9.5,4.5,3.5,7.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
17,La Covatilla Sierra de Béjar,1990,2368,26.8,8.6,18.2,0.0,NaN,3.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN
18,Valdesquí,1860,2278,22.3,18.8,3.5,0.0,NaN,13.0,38.0,NaN,NaN,NaN,NaN,09:00,16:30
19,Puerto Navacerrada,1703,2174,10.0,3.0,6.0,1.0,NaN,5.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN
20,Javalambre,1650,2000,15.0,14.0,1.0,0.0,NaN,7.0,36.0,NaN,NaN,NaN,NaN,09:00,17:00
21,Fuentes de Invierno,1487,1950,8.8,4.2,3.3,1.3,NaN,4.0,27.0,2021-12-04,2022-04-03,early December,NaN,09:00,16:45
22,Manzaneda,1505,1760,10.0,8.0,2.0,0.0,NaN,6.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN
23,Valdelinares (Sierra de Gúdar),1737,1979,17.0,10.0,7.0,0.0,NaN,9.0,37.5,NaN,NaN,early December,NaN,08:30,17:00
24,Vallter 2000,1959,2535,10.4,5.4,4.0,1.0,6.3,8.0,27.0,NaN,NaN,early December,NaN,09:00,16:45
25,Leitariegos,1513,1800,7.0,4.0,3.0,0.0,NaN,6.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN
26,Pleta del Prat Tavascan,1712,2197,5.0,1.0,4.0,0.0,NaN,2.0,22.0,NaN,NaN,NaN,NaN,09:00,16:00
27,Vall de Núria,1964,2260,7.6,4.1,2.5,1.0,NaN,5.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN
28,San Isidro Zona Salencias,1502,1670,6.5,2.9,3.6,0.0,NaN,4.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
29,Rasos de Peguera,1825,2035,5.0,3.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Madrid Snow Zone,667,705,0.3,0.2,0.1,0.0,NaN,3.0,39.0,NaN,NaN,Year-round__,NaN,09:00,22:00
31,Punto de Nieve Santa Inés,1753,1832,1.8,1.0,0.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [270]:
dfesp['Country']=dfesp['Name'].apply(coger_loc)

Estació Baqueira Beret, C-28, Baqueira, Naut Aran, Val d'Aran, Lleida, Catalunya, 25539, España
Formigal, Sallent de Gállego, Alto Gállego, Huesca, Aragón, 22640, España
GI-400 Carretera de Das a la Molina i Collada de Toses - C-663, Masella, Alp, Cerdanya, Girona, Catalunya, 17538, España
Plaza de Pradollano, Pradollano, Monachil, Comarca de la Vega de Granada, Granada, Andalucía, 18196, España
Cerler, Benasque, La Ribagorza, Huesca, Aragón, 22449, España
Panticosa, Alto Gállego, Huesca, Aragón, España
Taüll, la Vall de Boí, Alta Ribagorça, Lleida, Catalunya, 25528, España
Espot Esquí, Espot, Pallars Sobirà, Lleida, Catalunya, España
Candanchú, N-330-b, Candanchú, Aísa, La Jacetania, Huesca, Aragón, 22889, España
Ástún, Ísafjarðarbær, Vestfirðir, Ísland
Port del Comte, la Coma i la Pedra, Solsonès, Lleida, Catalunya, 25282, España
Estación de esquí de Valdezcaray, Carretera de Valdezcaray, Ezcaray, La Rioja, España
Port Ainé, Soriguera, Pallars Sobirà, Lleida, Catalunya, 25566, España
La Pinilla, Puebla de la Sierra, Sierra Norte, Comunidad de Madrid, España
Estación de Esquí y Montaña Alto Campoo, Senda de la Sierra de Híjar, Hermandad de Campoo de Suso, Campoo-Los Valles, Cantabria, 39573, España
Valgrande, Carretera de Valgrande - Pajares, El Brañillín, Lena, Asturias / Asturies, 24690, España
Estación de esquí Sierra de Béjar - La Covatilla, Navacarros, Salamanca, Castilla y León, España
Valdesquí, Pradera I, Rascafría, Sierra Norte, Comunidad de Madrid, España
Pto. Navacerrada, Calle Vitoria, Puerto de Navacerrada, Los Baldíos, Cuenca del Guadarrama, Comunidad de Madrid, España
Javalambre, La Puebla de Valverde, Gúdar-Javalambre, Teruel, Aragón, España
Fuentes de Invierno, Acceso a Fuentes de Invierno, La Raya, Aller, Asturias / Asturies, España
Manzaneda, Terra de Trives, Ourense, Galicia, España
Sierra de Gúdar, VF-TE-01, Valdelinares, Gúdar-Javalambre, Teruel, Aragón, España
Valter2000, Setcases, Ripollès, Girona, Catalunya, 17869, España
El Puertu de L.leitariegos, Cangas del Narcea, España
la Vall de Núria, Olesa de Montserrat, Baix Llobregat, Barcelona, Catalunya, 08295, España
Rasos de Peguera, Avinguda de Can Mir, Castellnou, Rubí, Vallès Occidental, Barcelona, Catalunya, 08194, España
Punto de Nieve Santa Inés, Carretera de Vinuesa a Montenegro, Vinuesa, Soria, Castilla y León, España