In [1]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from selenium.webdriver.chrome.options import Options
import sys
import regex as re
import pandas as pd

In [2]:
nombres = pd.read_csv('Data/name.csv')
Metros = pd.read_csv('Data/metros.csv')
pistas = pd.read_csv('Data/pistas.csv')
remontes = pd.read_csv('Data/remontes.csv')
precios = pd.read_csv('Data/precios.csv')
temporada = pd.read_csv('Data/Season.csv')

In [3]:
dfINAL = pd.concat([nombres,Metros,pistas,remontes,precios,temporada], axis=1)

In [4]:
dfINAL = dfINAL.drop('Unnamed: 0', 1)

<ipython-input-4-448f5175fe73>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  dfINAL = dfINAL.drop('Unnamed: 0', 1)

In [5]:
dfINAL

,Nombre,Minima Altura,Maxima Altura,Pistas_Totales,Easy,Intermediate,Difficult,Aditional_Routes,Lifts,Adults,Youth,Children,Current_season_start,Current_season_finish,General_season_start,General_season_finish,Opening_time,Closing_time
0,Lermoos – Grubigstein,__1004 m,2100 m,27.3,12.8,12.6,1.9,1.7,8.0,49.50,39.50,"25,-__",2021-12-04,2022-04-18__,early December,mid April__,08:30,16:30__
1,Latemar – Obereggen/Pampeago/Predazzo,__ 1540 m,2388 m,49.0,9.3,32.8,6.9,NaN,18.0,"52,-","37,-__",NaN,2021-11-26,2022-04-18__,late November,late April__,08:30,16:30__
2,Arosa Lenzerheide,__1229 m,2865 m,225.0,110.0,87.0,28.0,NaN,43.0,"78,- approx.","51,- approx.","25,-__",2021-10-30,2022-04-18__,early November,mid April__,08:30,16:30__
3,Ischgl/Samnaun – Silvretta Arena,__1360 m,2872 m,239.0,47.0,143.0,49.0,15.0,41.0,"55,-",34.50__,NaN,2021-11-25,2022-05-01__,late November,early May__,08:30,16:00__
4,Ski Juwel Alpbachtal Wildschönau,__830 m,2025 m,90.9,25.1,53.1,12.7,16.3,46.0,"51,-","41,-",25.50__,2021-12-03,2022-04-18__,mid December,mid April__,08:30,16:00__
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pallas,__440 m,780 m,12.0,8.0,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00__
933,Eikedalen,__457 m,918 m,15.0,10.0,5.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:00,16:00__
934,Valbella – Gallio,__1100 m,1311 m,11.2,8.0,2.5,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
935,Caldirola – Monte Gropà,__1075 m,1429 m,5.9,4.0,1.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08:30,17:00__
936,Kreuzberg – Bischofsheim an der Rhön,__610 m,928 m,13.0,5.0,8.0,0.0,NaN,4.0,"17,-","13,-__",NaN,2021-12-25,2022-03-13__,mid December,mid March__,09:00,17:00__

In [6]:
def limpia_col(dfcol):
    for i in dfcol:
        a = dfcol.str.extract('((\d+)+(\.\d+)|(\d+))', flags=0)
        a = a.rename(columns={0:"Primera"})
    return a.Primera

In [7]:
dfINAL.columns

Index(['Nombre', 'Minima Altura', 'Maxima Altura', 'Pistas_Totales', 'Easy',
       'Intermediate', 'Difficult', 'Aditional_Routes', 'Lifts', 'Adults',
       'Youth', 'Children', 'Current_season_start', 'Current_season_finish',
       'General_season_start', 'General_season_finish', 'Opening_time',
       'Closing_time'],
      dtype='object')

In [8]:
def limpia_col(df):
    a = limpia_col(dfINAL['Minima Altura'])
    b = limpia_col(dfINAL['Maxima Altura'])
    i = limpia_col(dfINAL['Adults'])
    j = limpia_col(dfINAL['Children'])
    k = limpia_col(dfINAL['Youth'])